### ISSUE TITLE
Questions about the "Rebound"-Editor...

### ISSUE THREAD

**Issue by aismann** [DelinWorks/Rebound#14]
1) It is multi-tile-set supported (Axmol needs an fix/feature)?
2) Can it used for any kind of tiles (size)?

**Comment by DelinWorks** [comment]
Yes! it supports multi-tileset rendering and uses the same technique as Tiled editor, if the first tileset has 64 individual tiles in it the firstGid of the next tileset will be 65 and the system will create another draw call for that other tileset, maybe I can use OpenGL texture arrays but I need knowledge about Metal too or else how Can I support iOS? 

Yes! it supports any kind of tileset size and it will automatically adapt the texture sizes
it can be as simple as this statement
```cpp
tilesetArr = TileSystem::TilesetArray::create({ 16, 16 });
```

**Comment by aismann** [comment]
This is an example screenshot:

https://user-images.githubusercontent.com/8652787/181373211-1dc7af7e-cdf0-4f18-8e7c-8778f6251f58.png

**Comment by DelinWorks** [comment]
Don't worry when I finish it I'll make menus and what not
